// Generated by gencpp from file webots_demo/field_get_string.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_FIELD_GET_STRING_H
#define WEBOTS_DEMO_MESSAGE_FIELD_GET_STRING_H

#include <ros/service_traits.h>


#include <webots_demo/field_get_stringRequest.h>
#include <webots_demo/field_get_stringResponse.h>


namespace webots_demo
{

struct field_get_string
{

typedef field_get_stringRequest Request;
typedef field_get_stringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_get_string
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::field_get_string > {
  static const char* value()
  {
    return "a1926692206ecc55a7a2d2564a578c89";
  }

  static const char* value(const ::webots_demo::field_get_string&) { return value(); }
};

template<>
struct DataType< ::webots_demo::field_get_string > {
  static const char* value()
  {
    return "webots_demo/field_get_string";
  }

  static const char* value(const ::webots_demo::field_get_string&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::field_get_stringRequest> should match
// service_traits::MD5Sum< ::webots_demo::field_get_string >
template<>
struct MD5Sum< ::webots_demo::field_get_stringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_get_string >::value();
  }
  static const char* value(const ::webots_demo::field_get_stringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_get_stringRequest> should match
// service_traits::DataType< ::webots_demo::field_get_string >
template<>
struct DataType< ::webots_demo::field_get_stringRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_get_string >::value();
  }
  static const char* value(const ::webots_demo::field_get_stringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::field_get_stringResponse> should match
// service_traits::MD5Sum< ::webots_demo::field_get_string >
template<>
struct MD5Sum< ::webots_demo::field_get_stringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_get_string >::value();
  }
  static const char* value(const ::webots_demo::field_get_stringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_get_stringResponse> should match
// service_traits::DataType< ::webots_demo::field_get_string >
template<>
struct DataType< ::webots_demo::field_get_stringResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_get_string >::value();
  }
  static const char* value(const ::webots_demo::field_get_stringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_FIELD_GET_STRING_H
