// Generated by gencpp from file webots_demo/field_set_vec3f.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_FIELD_SET_VEC3F_H
#define WEBOTS_DEMO_MESSAGE_FIELD_SET_VEC3F_H

#include <ros/service_traits.h>


#include <webots_demo/field_set_vec3fRequest.h>
#include <webots_demo/field_set_vec3fResponse.h>


namespace webots_demo
{

struct field_set_vec3f
{

typedef field_set_vec3fRequest Request;
typedef field_set_vec3fResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_set_vec3f
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::field_set_vec3f > {
  static const char* value()
  {
    return "e0edef5860d282e4d35ef264e28feecc";
  }

  static const char* value(const ::webots_demo::field_set_vec3f&) { return value(); }
};

template<>
struct DataType< ::webots_demo::field_set_vec3f > {
  static const char* value()
  {
    return "webots_demo/field_set_vec3f";
  }

  static const char* value(const ::webots_demo::field_set_vec3f&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::field_set_vec3fRequest> should match
// service_traits::MD5Sum< ::webots_demo::field_set_vec3f >
template<>
struct MD5Sum< ::webots_demo::field_set_vec3fRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_set_vec3f >::value();
  }
  static const char* value(const ::webots_demo::field_set_vec3fRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_set_vec3fRequest> should match
// service_traits::DataType< ::webots_demo::field_set_vec3f >
template<>
struct DataType< ::webots_demo::field_set_vec3fRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_set_vec3f >::value();
  }
  static const char* value(const ::webots_demo::field_set_vec3fRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::field_set_vec3fResponse> should match
// service_traits::MD5Sum< ::webots_demo::field_set_vec3f >
template<>
struct MD5Sum< ::webots_demo::field_set_vec3fResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_set_vec3f >::value();
  }
  static const char* value(const ::webots_demo::field_set_vec3fResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_set_vec3fResponse> should match
// service_traits::DataType< ::webots_demo::field_set_vec3f >
template<>
struct DataType< ::webots_demo::field_set_vec3fResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_set_vec3f >::value();
  }
  static const char* value(const ::webots_demo::field_set_vec3fResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_FIELD_SET_VEC3F_H
