// Generated by gencpp from file webots_demo/field_set_float.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_FIELD_SET_FLOAT_H
#define WEBOTS_DEMO_MESSAGE_FIELD_SET_FLOAT_H

#include <ros/service_traits.h>


#include <webots_demo/field_set_floatRequest.h>
#include <webots_demo/field_set_floatResponse.h>


namespace webots_demo
{

struct field_set_float
{

typedef field_set_floatRequest Request;
typedef field_set_floatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_set_float
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::field_set_float > {
  static const char* value()
  {
    return "4e40976b84f091a5cb0ce60a329c40a3";
  }

  static const char* value(const ::webots_demo::field_set_float&) { return value(); }
};

template<>
struct DataType< ::webots_demo::field_set_float > {
  static const char* value()
  {
    return "webots_demo/field_set_float";
  }

  static const char* value(const ::webots_demo::field_set_float&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::field_set_floatRequest> should match
// service_traits::MD5Sum< ::webots_demo::field_set_float >
template<>
struct MD5Sum< ::webots_demo::field_set_floatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_set_float >::value();
  }
  static const char* value(const ::webots_demo::field_set_floatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_set_floatRequest> should match
// service_traits::DataType< ::webots_demo::field_set_float >
template<>
struct DataType< ::webots_demo::field_set_floatRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_set_float >::value();
  }
  static const char* value(const ::webots_demo::field_set_floatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::field_set_floatResponse> should match
// service_traits::MD5Sum< ::webots_demo::field_set_float >
template<>
struct MD5Sum< ::webots_demo::field_set_floatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_set_float >::value();
  }
  static const char* value(const ::webots_demo::field_set_floatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_set_floatResponse> should match
// service_traits::DataType< ::webots_demo::field_set_float >
template<>
struct DataType< ::webots_demo::field_set_floatResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_set_float >::value();
  }
  static const char* value(const ::webots_demo::field_set_floatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_FIELD_SET_FLOAT_H
