// Generated by gencpp from file webots_demo/field_set_bool.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_FIELD_SET_BOOL_H
#define WEBOTS_DEMO_MESSAGE_FIELD_SET_BOOL_H

#include <ros/service_traits.h>


#include <webots_demo/field_set_boolRequest.h>
#include <webots_demo/field_set_boolResponse.h>


namespace webots_demo
{

struct field_set_bool
{

typedef field_set_boolRequest Request;
typedef field_set_boolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_set_bool
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::field_set_bool > {
  static const char* value()
  {
    return "7a9b164ddc41cfd8469ce0cd504f469e";
  }

  static const char* value(const ::webots_demo::field_set_bool&) { return value(); }
};

template<>
struct DataType< ::webots_demo::field_set_bool > {
  static const char* value()
  {
    return "webots_demo/field_set_bool";
  }

  static const char* value(const ::webots_demo::field_set_bool&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::field_set_boolRequest> should match
// service_traits::MD5Sum< ::webots_demo::field_set_bool >
template<>
struct MD5Sum< ::webots_demo::field_set_boolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_set_bool >::value();
  }
  static const char* value(const ::webots_demo::field_set_boolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_set_boolRequest> should match
// service_traits::DataType< ::webots_demo::field_set_bool >
template<>
struct DataType< ::webots_demo::field_set_boolRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_set_bool >::value();
  }
  static const char* value(const ::webots_demo::field_set_boolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::field_set_boolResponse> should match
// service_traits::MD5Sum< ::webots_demo::field_set_bool >
template<>
struct MD5Sum< ::webots_demo::field_set_boolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_set_bool >::value();
  }
  static const char* value(const ::webots_demo::field_set_boolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_set_boolResponse> should match
// service_traits::DataType< ::webots_demo::field_set_bool >
template<>
struct DataType< ::webots_demo::field_set_boolResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_set_bool >::value();
  }
  static const char* value(const ::webots_demo::field_set_boolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_FIELD_SET_BOOL_H
