// Generated by gencpp from file webots_demo/field_get_type_name.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_FIELD_GET_TYPE_NAME_H
#define WEBOTS_DEMO_MESSAGE_FIELD_GET_TYPE_NAME_H

#include <ros/service_traits.h>


#include <webots_demo/field_get_type_nameRequest.h>
#include <webots_demo/field_get_type_nameResponse.h>


namespace webots_demo
{

struct field_get_type_name
{

typedef field_get_type_nameRequest Request;
typedef field_get_type_nameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_get_type_name
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::field_get_type_name > {
  static const char* value()
  {
    return "5a98464d3ca05386300217ec41ec161f";
  }

  static const char* value(const ::webots_demo::field_get_type_name&) { return value(); }
};

template<>
struct DataType< ::webots_demo::field_get_type_name > {
  static const char* value()
  {
    return "webots_demo/field_get_type_name";
  }

  static const char* value(const ::webots_demo::field_get_type_name&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::field_get_type_nameRequest> should match
// service_traits::MD5Sum< ::webots_demo::field_get_type_name >
template<>
struct MD5Sum< ::webots_demo::field_get_type_nameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_get_type_name >::value();
  }
  static const char* value(const ::webots_demo::field_get_type_nameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_get_type_nameRequest> should match
// service_traits::DataType< ::webots_demo::field_get_type_name >
template<>
struct DataType< ::webots_demo::field_get_type_nameRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_get_type_name >::value();
  }
  static const char* value(const ::webots_demo::field_get_type_nameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::field_get_type_nameResponse> should match
// service_traits::MD5Sum< ::webots_demo::field_get_type_name >
template<>
struct MD5Sum< ::webots_demo::field_get_type_nameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_get_type_name >::value();
  }
  static const char* value(const ::webots_demo::field_get_type_nameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_get_type_nameResponse> should match
// service_traits::DataType< ::webots_demo::field_get_type_name >
template<>
struct DataType< ::webots_demo::field_get_type_nameResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_get_type_name >::value();
  }
  static const char* value(const ::webots_demo::field_get_type_nameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_FIELD_GET_TYPE_NAME_H
