// Generated by gencpp from file webots_demo/field_remove.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_FIELD_REMOVE_H
#define WEBOTS_DEMO_MESSAGE_FIELD_REMOVE_H

#include <ros/service_traits.h>


#include <webots_demo/field_removeRequest.h>
#include <webots_demo/field_removeResponse.h>


namespace webots_demo
{

struct field_remove
{

typedef field_removeRequest Request;
typedef field_removeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_remove
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::field_remove > {
  static const char* value()
  {
    return "722e922dddeea014e5ea68aa3843aeba";
  }

  static const char* value(const ::webots_demo::field_remove&) { return value(); }
};

template<>
struct DataType< ::webots_demo::field_remove > {
  static const char* value()
  {
    return "webots_demo/field_remove";
  }

  static const char* value(const ::webots_demo::field_remove&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::field_removeRequest> should match
// service_traits::MD5Sum< ::webots_demo::field_remove >
template<>
struct MD5Sum< ::webots_demo::field_removeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_remove >::value();
  }
  static const char* value(const ::webots_demo::field_removeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_removeRequest> should match
// service_traits::DataType< ::webots_demo::field_remove >
template<>
struct DataType< ::webots_demo::field_removeRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_remove >::value();
  }
  static const char* value(const ::webots_demo::field_removeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::field_removeResponse> should match
// service_traits::MD5Sum< ::webots_demo::field_remove >
template<>
struct MD5Sum< ::webots_demo::field_removeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_remove >::value();
  }
  static const char* value(const ::webots_demo::field_removeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_removeResponse> should match
// service_traits::DataType< ::webots_demo::field_remove >
template<>
struct DataType< ::webots_demo::field_removeResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_remove >::value();
  }
  static const char* value(const ::webots_demo::field_removeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_FIELD_REMOVE_H
