// Generated by gencpp from file webots_demo/field_get_color.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_FIELD_GET_COLOR_H
#define WEBOTS_DEMO_MESSAGE_FIELD_GET_COLOR_H

#include <ros/service_traits.h>


#include <webots_demo/field_get_colorRequest.h>
#include <webots_demo/field_get_colorResponse.h>


namespace webots_demo
{

struct field_get_color
{

typedef field_get_colorRequest Request;
typedef field_get_colorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_get_color
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::field_get_color > {
  static const char* value()
  {
    return "4920aae633f7f96feac03b4ce89984d5";
  }

  static const char* value(const ::webots_demo::field_get_color&) { return value(); }
};

template<>
struct DataType< ::webots_demo::field_get_color > {
  static const char* value()
  {
    return "webots_demo/field_get_color";
  }

  static const char* value(const ::webots_demo::field_get_color&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::field_get_colorRequest> should match
// service_traits::MD5Sum< ::webots_demo::field_get_color >
template<>
struct MD5Sum< ::webots_demo::field_get_colorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_get_color >::value();
  }
  static const char* value(const ::webots_demo::field_get_colorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_get_colorRequest> should match
// service_traits::DataType< ::webots_demo::field_get_color >
template<>
struct DataType< ::webots_demo::field_get_colorRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_get_color >::value();
  }
  static const char* value(const ::webots_demo::field_get_colorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::field_get_colorResponse> should match
// service_traits::MD5Sum< ::webots_demo::field_get_color >
template<>
struct MD5Sum< ::webots_demo::field_get_colorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_get_color >::value();
  }
  static const char* value(const ::webots_demo::field_get_colorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_get_colorResponse> should match
// service_traits::DataType< ::webots_demo::field_get_color >
template<>
struct DataType< ::webots_demo::field_get_colorResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_get_color >::value();
  }
  static const char* value(const ::webots_demo::field_get_colorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_FIELD_GET_COLOR_H
