// Generated by gencpp from file webots_demo/field_import_node_from_string.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_FIELD_IMPORT_NODE_FROM_STRING_H
#define WEBOTS_DEMO_MESSAGE_FIELD_IMPORT_NODE_FROM_STRING_H

#include <ros/service_traits.h>


#include <webots_demo/field_import_node_from_stringRequest.h>
#include <webots_demo/field_import_node_from_stringResponse.h>


namespace webots_demo
{

struct field_import_node_from_string
{

typedef field_import_node_from_stringRequest Request;
typedef field_import_node_from_stringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_import_node_from_string
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::field_import_node_from_string > {
  static const char* value()
  {
    return "f47a09684279b85c2c8ae161048ce7d0";
  }

  static const char* value(const ::webots_demo::field_import_node_from_string&) { return value(); }
};

template<>
struct DataType< ::webots_demo::field_import_node_from_string > {
  static const char* value()
  {
    return "webots_demo/field_import_node_from_string";
  }

  static const char* value(const ::webots_demo::field_import_node_from_string&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::field_import_node_from_stringRequest> should match
// service_traits::MD5Sum< ::webots_demo::field_import_node_from_string >
template<>
struct MD5Sum< ::webots_demo::field_import_node_from_stringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_import_node_from_string >::value();
  }
  static const char* value(const ::webots_demo::field_import_node_from_stringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_import_node_from_stringRequest> should match
// service_traits::DataType< ::webots_demo::field_import_node_from_string >
template<>
struct DataType< ::webots_demo::field_import_node_from_stringRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_import_node_from_string >::value();
  }
  static const char* value(const ::webots_demo::field_import_node_from_stringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::field_import_node_from_stringResponse> should match
// service_traits::MD5Sum< ::webots_demo::field_import_node_from_string >
template<>
struct MD5Sum< ::webots_demo::field_import_node_from_stringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_import_node_from_string >::value();
  }
  static const char* value(const ::webots_demo::field_import_node_from_stringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_import_node_from_stringResponse> should match
// service_traits::DataType< ::webots_demo::field_import_node_from_string >
template<>
struct DataType< ::webots_demo::field_import_node_from_stringResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_import_node_from_string >::value();
  }
  static const char* value(const ::webots_demo::field_import_node_from_stringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_FIELD_IMPORT_NODE_FROM_STRING_H
