// Generated by gencpp from file webots_demo/field_set_rotation.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_FIELD_SET_ROTATION_H
#define WEBOTS_DEMO_MESSAGE_FIELD_SET_ROTATION_H

#include <ros/service_traits.h>


#include <webots_demo/field_set_rotationRequest.h>
#include <webots_demo/field_set_rotationResponse.h>


namespace webots_demo
{

struct field_set_rotation
{

typedef field_set_rotationRequest Request;
typedef field_set_rotationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_set_rotation
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::field_set_rotation > {
  static const char* value()
  {
    return "f7b9003dace87295f2b9eb1dc57c4294";
  }

  static const char* value(const ::webots_demo::field_set_rotation&) { return value(); }
};

template<>
struct DataType< ::webots_demo::field_set_rotation > {
  static const char* value()
  {
    return "webots_demo/field_set_rotation";
  }

  static const char* value(const ::webots_demo::field_set_rotation&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::field_set_rotationRequest> should match
// service_traits::MD5Sum< ::webots_demo::field_set_rotation >
template<>
struct MD5Sum< ::webots_demo::field_set_rotationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_set_rotation >::value();
  }
  static const char* value(const ::webots_demo::field_set_rotationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_set_rotationRequest> should match
// service_traits::DataType< ::webots_demo::field_set_rotation >
template<>
struct DataType< ::webots_demo::field_set_rotationRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_set_rotation >::value();
  }
  static const char* value(const ::webots_demo::field_set_rotationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::field_set_rotationResponse> should match
// service_traits::MD5Sum< ::webots_demo::field_set_rotation >
template<>
struct MD5Sum< ::webots_demo::field_set_rotationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::field_set_rotation >::value();
  }
  static const char* value(const ::webots_demo::field_set_rotationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::field_set_rotationResponse> should match
// service_traits::DataType< ::webots_demo::field_set_rotation >
template<>
struct DataType< ::webots_demo::field_set_rotationResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::field_set_rotation >::value();
  }
  static const char* value(const ::webots_demo::field_set_rotationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_FIELD_SET_ROTATION_H
