// Generated by gencpp from file webots_demo/get_string.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_GET_STRING_H
#define WEBOTS_DEMO_MESSAGE_GET_STRING_H

#include <ros/service_traits.h>


#include <webots_demo/get_stringRequest.h>
#include <webots_demo/get_stringResponse.h>


namespace webots_demo
{

struct get_string
{

typedef get_stringRequest Request;
typedef get_stringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_string
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::get_string > {
  static const char* value()
  {
    return "3bf99d9257a34f6cdd01cd192a62b3df";
  }

  static const char* value(const ::webots_demo::get_string&) { return value(); }
};

template<>
struct DataType< ::webots_demo::get_string > {
  static const char* value()
  {
    return "webots_demo/get_string";
  }

  static const char* value(const ::webots_demo::get_string&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::get_stringRequest> should match
// service_traits::MD5Sum< ::webots_demo::get_string >
template<>
struct MD5Sum< ::webots_demo::get_stringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::get_string >::value();
  }
  static const char* value(const ::webots_demo::get_stringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::get_stringRequest> should match
// service_traits::DataType< ::webots_demo::get_string >
template<>
struct DataType< ::webots_demo::get_stringRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::get_string >::value();
  }
  static const char* value(const ::webots_demo::get_stringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::get_stringResponse> should match
// service_traits::MD5Sum< ::webots_demo::get_string >
template<>
struct MD5Sum< ::webots_demo::get_stringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::get_string >::value();
  }
  static const char* value(const ::webots_demo::get_stringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::get_stringResponse> should match
// service_traits::DataType< ::webots_demo::get_string >
template<>
struct DataType< ::webots_demo::get_stringResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::get_string >::value();
  }
  static const char* value(const ::webots_demo::get_stringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_GET_STRING_H
