// Generated by gencpp from file webots_demo/node_get_parent_node.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_NODE_GET_PARENT_NODE_H
#define WEBOTS_DEMO_MESSAGE_NODE_GET_PARENT_NODE_H

#include <ros/service_traits.h>


#include <webots_demo/node_get_parent_nodeRequest.h>
#include <webots_demo/node_get_parent_nodeResponse.h>


namespace webots_demo
{

struct node_get_parent_node
{

typedef node_get_parent_nodeRequest Request;
typedef node_get_parent_nodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_parent_node
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::node_get_parent_node > {
  static const char* value()
  {
    return "818a5363f8ab50910f19b3cf3acc208b";
  }

  static const char* value(const ::webots_demo::node_get_parent_node&) { return value(); }
};

template<>
struct DataType< ::webots_demo::node_get_parent_node > {
  static const char* value()
  {
    return "webots_demo/node_get_parent_node";
  }

  static const char* value(const ::webots_demo::node_get_parent_node&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::node_get_parent_nodeRequest> should match
// service_traits::MD5Sum< ::webots_demo::node_get_parent_node >
template<>
struct MD5Sum< ::webots_demo::node_get_parent_nodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::node_get_parent_node >::value();
  }
  static const char* value(const ::webots_demo::node_get_parent_nodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::node_get_parent_nodeRequest> should match
// service_traits::DataType< ::webots_demo::node_get_parent_node >
template<>
struct DataType< ::webots_demo::node_get_parent_nodeRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::node_get_parent_node >::value();
  }
  static const char* value(const ::webots_demo::node_get_parent_nodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::node_get_parent_nodeResponse> should match
// service_traits::MD5Sum< ::webots_demo::node_get_parent_node >
template<>
struct MD5Sum< ::webots_demo::node_get_parent_nodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::node_get_parent_node >::value();
  }
  static const char* value(const ::webots_demo::node_get_parent_nodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::node_get_parent_nodeResponse> should match
// service_traits::DataType< ::webots_demo::node_get_parent_node >
template<>
struct DataType< ::webots_demo::node_get_parent_nodeResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::node_get_parent_node >::value();
  }
  static const char* value(const ::webots_demo::node_get_parent_nodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_NODE_GET_PARENT_NODE_H
