// Generated by gencpp from file webots_demo/node_get_contact_point.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_NODE_GET_CONTACT_POINT_H
#define WEBOTS_DEMO_MESSAGE_NODE_GET_CONTACT_POINT_H

#include <ros/service_traits.h>


#include <webots_demo/node_get_contact_pointRequest.h>
#include <webots_demo/node_get_contact_pointResponse.h>


namespace webots_demo
{

struct node_get_contact_point
{

typedef node_get_contact_pointRequest Request;
typedef node_get_contact_pointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_contact_point
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::node_get_contact_point > {
  static const char* value()
  {
    return "d85a7c32d5696fcbf69df9280ddce70d";
  }

  static const char* value(const ::webots_demo::node_get_contact_point&) { return value(); }
};

template<>
struct DataType< ::webots_demo::node_get_contact_point > {
  static const char* value()
  {
    return "webots_demo/node_get_contact_point";
  }

  static const char* value(const ::webots_demo::node_get_contact_point&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::node_get_contact_pointRequest> should match
// service_traits::MD5Sum< ::webots_demo::node_get_contact_point >
template<>
struct MD5Sum< ::webots_demo::node_get_contact_pointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::node_get_contact_point >::value();
  }
  static const char* value(const ::webots_demo::node_get_contact_pointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::node_get_contact_pointRequest> should match
// service_traits::DataType< ::webots_demo::node_get_contact_point >
template<>
struct DataType< ::webots_demo::node_get_contact_pointRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::node_get_contact_point >::value();
  }
  static const char* value(const ::webots_demo::node_get_contact_pointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::node_get_contact_pointResponse> should match
// service_traits::MD5Sum< ::webots_demo::node_get_contact_point >
template<>
struct MD5Sum< ::webots_demo::node_get_contact_pointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::node_get_contact_point >::value();
  }
  static const char* value(const ::webots_demo::node_get_contact_pointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::node_get_contact_pointResponse> should match
// service_traits::DataType< ::webots_demo::node_get_contact_point >
template<>
struct DataType< ::webots_demo::node_get_contact_pointResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::node_get_contact_point >::value();
  }
  static const char* value(const ::webots_demo::node_get_contact_pointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_NODE_GET_CONTACT_POINT_H
