// Generated by gencpp from file webots_demo/node_get_id.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_NODE_GET_ID_H
#define WEBOTS_DEMO_MESSAGE_NODE_GET_ID_H

#include <ros/service_traits.h>


#include <webots_demo/node_get_idRequest.h>
#include <webots_demo/node_get_idResponse.h>


namespace webots_demo
{

struct node_get_id
{

typedef node_get_idRequest Request;
typedef node_get_idResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_id
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::node_get_id > {
  static const char* value()
  {
    return "16a06b427b76c7c64b73962f4f092416";
  }

  static const char* value(const ::webots_demo::node_get_id&) { return value(); }
};

template<>
struct DataType< ::webots_demo::node_get_id > {
  static const char* value()
  {
    return "webots_demo/node_get_id";
  }

  static const char* value(const ::webots_demo::node_get_id&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::node_get_idRequest> should match
// service_traits::MD5Sum< ::webots_demo::node_get_id >
template<>
struct MD5Sum< ::webots_demo::node_get_idRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::node_get_id >::value();
  }
  static const char* value(const ::webots_demo::node_get_idRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::node_get_idRequest> should match
// service_traits::DataType< ::webots_demo::node_get_id >
template<>
struct DataType< ::webots_demo::node_get_idRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::node_get_id >::value();
  }
  static const char* value(const ::webots_demo::node_get_idRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::node_get_idResponse> should match
// service_traits::MD5Sum< ::webots_demo::node_get_id >
template<>
struct MD5Sum< ::webots_demo::node_get_idResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::node_get_id >::value();
  }
  static const char* value(const ::webots_demo::node_get_idResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::node_get_idResponse> should match
// service_traits::DataType< ::webots_demo::node_get_id >
template<>
struct DataType< ::webots_demo::node_get_idResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::node_get_id >::value();
  }
  static const char* value(const ::webots_demo::node_get_idResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_NODE_GET_ID_H
