// Generated by gencpp from file webots_demo/node_get_position.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_NODE_GET_POSITION_H
#define WEBOTS_DEMO_MESSAGE_NODE_GET_POSITION_H

#include <ros/service_traits.h>


#include <webots_demo/node_get_positionRequest.h>
#include <webots_demo/node_get_positionResponse.h>


namespace webots_demo
{

struct node_get_position
{

typedef node_get_positionRequest Request;
typedef node_get_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_position
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::node_get_position > {
  static const char* value()
  {
    return "a7fd7bab623637fe72e0ee179149fc41";
  }

  static const char* value(const ::webots_demo::node_get_position&) { return value(); }
};

template<>
struct DataType< ::webots_demo::node_get_position > {
  static const char* value()
  {
    return "webots_demo/node_get_position";
  }

  static const char* value(const ::webots_demo::node_get_position&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::node_get_positionRequest> should match
// service_traits::MD5Sum< ::webots_demo::node_get_position >
template<>
struct MD5Sum< ::webots_demo::node_get_positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::node_get_position >::value();
  }
  static const char* value(const ::webots_demo::node_get_positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::node_get_positionRequest> should match
// service_traits::DataType< ::webots_demo::node_get_position >
template<>
struct DataType< ::webots_demo::node_get_positionRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::node_get_position >::value();
  }
  static const char* value(const ::webots_demo::node_get_positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::node_get_positionResponse> should match
// service_traits::MD5Sum< ::webots_demo::node_get_position >
template<>
struct MD5Sum< ::webots_demo::node_get_positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::node_get_position >::value();
  }
  static const char* value(const ::webots_demo::node_get_positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::node_get_positionResponse> should match
// service_traits::DataType< ::webots_demo::node_get_position >
template<>
struct DataType< ::webots_demo::node_get_positionResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::node_get_position >::value();
  }
  static const char* value(const ::webots_demo::node_get_positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_NODE_GET_POSITION_H
