// Generated by gencpp from file webots_demo/speaker_speak.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_SPEAKER_SPEAK_H
#define WEBOTS_DEMO_MESSAGE_SPEAKER_SPEAK_H

#include <ros/service_traits.h>


#include <webots_demo/speaker_speakRequest.h>
#include <webots_demo/speaker_speakResponse.h>


namespace webots_demo
{

struct speaker_speak
{

typedef speaker_speakRequest Request;
typedef speaker_speakResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct speaker_speak
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::speaker_speak > {
  static const char* value()
  {
    return "bc987d1a1839d594218b7c1d6a77ba5e";
  }

  static const char* value(const ::webots_demo::speaker_speak&) { return value(); }
};

template<>
struct DataType< ::webots_demo::speaker_speak > {
  static const char* value()
  {
    return "webots_demo/speaker_speak";
  }

  static const char* value(const ::webots_demo::speaker_speak&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::speaker_speakRequest> should match
// service_traits::MD5Sum< ::webots_demo::speaker_speak >
template<>
struct MD5Sum< ::webots_demo::speaker_speakRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::speaker_speak >::value();
  }
  static const char* value(const ::webots_demo::speaker_speakRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::speaker_speakRequest> should match
// service_traits::DataType< ::webots_demo::speaker_speak >
template<>
struct DataType< ::webots_demo::speaker_speakRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::speaker_speak >::value();
  }
  static const char* value(const ::webots_demo::speaker_speakRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::speaker_speakResponse> should match
// service_traits::MD5Sum< ::webots_demo::speaker_speak >
template<>
struct MD5Sum< ::webots_demo::speaker_speakResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::speaker_speak >::value();
  }
  static const char* value(const ::webots_demo::speaker_speakResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::speaker_speakResponse> should match
// service_traits::DataType< ::webots_demo::speaker_speak >
template<>
struct DataType< ::webots_demo::speaker_speakResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::speaker_speak >::value();
  }
  static const char* value(const ::webots_demo::speaker_speakResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_SPEAKER_SPEAK_H
