// Generated by gencpp from file webots_demo/supervisor_virtual_reality_headset_get_position.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_SUPERVISOR_VIRTUAL_REALITY_HEADSET_GET_POSITION_H
#define WEBOTS_DEMO_MESSAGE_SUPERVISOR_VIRTUAL_REALITY_HEADSET_GET_POSITION_H

#include <ros/service_traits.h>


#include <webots_demo/supervisor_virtual_reality_headset_get_positionRequest.h>
#include <webots_demo/supervisor_virtual_reality_headset_get_positionResponse.h>


namespace webots_demo
{

struct supervisor_virtual_reality_headset_get_position
{

typedef supervisor_virtual_reality_headset_get_positionRequest Request;
typedef supervisor_virtual_reality_headset_get_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct supervisor_virtual_reality_headset_get_position
} // namespace webots_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_demo::supervisor_virtual_reality_headset_get_position > {
  static const char* value()
  {
    return "a1afe95e0bfbfc2663c9e2313392f01d";
  }

  static const char* value(const ::webots_demo::supervisor_virtual_reality_headset_get_position&) { return value(); }
};

template<>
struct DataType< ::webots_demo::supervisor_virtual_reality_headset_get_position > {
  static const char* value()
  {
    return "webots_demo/supervisor_virtual_reality_headset_get_position";
  }

  static const char* value(const ::webots_demo::supervisor_virtual_reality_headset_get_position&) { return value(); }
};


// service_traits::MD5Sum< ::webots_demo::supervisor_virtual_reality_headset_get_positionRequest> should match
// service_traits::MD5Sum< ::webots_demo::supervisor_virtual_reality_headset_get_position >
template<>
struct MD5Sum< ::webots_demo::supervisor_virtual_reality_headset_get_positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::supervisor_virtual_reality_headset_get_position >::value();
  }
  static const char* value(const ::webots_demo::supervisor_virtual_reality_headset_get_positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::supervisor_virtual_reality_headset_get_positionRequest> should match
// service_traits::DataType< ::webots_demo::supervisor_virtual_reality_headset_get_position >
template<>
struct DataType< ::webots_demo::supervisor_virtual_reality_headset_get_positionRequest>
{
  static const char* value()
  {
    return DataType< ::webots_demo::supervisor_virtual_reality_headset_get_position >::value();
  }
  static const char* value(const ::webots_demo::supervisor_virtual_reality_headset_get_positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_demo::supervisor_virtual_reality_headset_get_positionResponse> should match
// service_traits::MD5Sum< ::webots_demo::supervisor_virtual_reality_headset_get_position >
template<>
struct MD5Sum< ::webots_demo::supervisor_virtual_reality_headset_get_positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_demo::supervisor_virtual_reality_headset_get_position >::value();
  }
  static const char* value(const ::webots_demo::supervisor_virtual_reality_headset_get_positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_demo::supervisor_virtual_reality_headset_get_positionResponse> should match
// service_traits::DataType< ::webots_demo::supervisor_virtual_reality_headset_get_position >
template<>
struct DataType< ::webots_demo::supervisor_virtual_reality_headset_get_positionResponse>
{
  static const char* value()
  {
    return DataType< ::webots_demo::supervisor_virtual_reality_headset_get_position >::value();
  }
  static const char* value(const ::webots_demo::supervisor_virtual_reality_headset_get_positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_SUPERVISOR_VIRTUAL_REALITY_HEADSET_GET_POSITION_H
